### ISSUE TITLE
Diff CH-bib-records in Big Muscat and in CH-Muscat

### ISSUE THREAD

**Issue by baccia** [rism-ch/rism-maintenance#17]
@xhero List differences between CH-bib-records in Big Muscat (corrected by ZR) and CH-bib-records in CH-Muscat.
@baccia Check by hand if there are corrections by ZR that might be automatically updated in CH-Muscat, or fields that should systematically be kept from the Big Muscat record when migrating (e.g., perhaps 300?)
When migrating, keep any fields that were added by ZR (e.g., additional 700s that are not in the CH-Muscat record)

**Comment by baccia** [comment]
Related issue:
Check character encoding errors in old CH-bib-records: 
e.g., "Ü" is rendered as "ö" in CH-Muscat, and is correct in Big Muscat
cf. 245 in 
http://www.rism-ch.org/admin/sources/400102457
https://muscat.rism.info/admin/sources/400102457

**Comment by xhero** [comment]
Is this a recurring issue? Or could it be something corrected in ZR?

**Comment by baccia** [comment]
Up to now (first day of work, 130 records checked out of 3900) I have spotted only Ü/ö.

**Comment by baccia** [comment]
Another character encoding error:
"à" is rendered as "á" in CH-Muscat, but is correct in Big Muscat
cf. 245 in
http://www.rism-ch.org/admin/sources/400104947
https://muscat.rism.info/admin/sources/400104947

**Comment by baccia** [comment]
Both character encoding errors are systematically recurring, as far as I could see - i.e., in all old CH-Muscat records "à" is rendered "á" and "Ü" is rendered "ö".
