### ISSUE TITLE
Links in 856 without link type

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/rism-maintenance#24]
Links without type are automatically displayed as digitized source in OPAC. F. e. https://muscat.rism.info/admin/sources/410006222/ in OPAC: http://www.rism.info/de/service/opac-suche.html

In CH-Lz all external links refer to another catalogue and should therefore be changed to "other".

Check all Swiss data.

**Comment by KlausKeil** [comment]
It is right to do so, but at the moment it will not change the RISM-OPAC entry. The BSB is working to differentiate between digital images and others but it is not jet made.
